# Generated by Django 3.2.2 on 2022-03-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('is_active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
