# Generated by Django 3.2.2 on 2022-03-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
